import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'
import "./globals.css";
import { Header } from "@/Header/Header";
import { Footer } from "@/Footer/Footer";
import { Menu } from "@/Menu/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const menuItems = [
    {
      id: 'home',
      path: 'home',
      text: 'Home'
    },
    {
      id: 'aboutus',
      path: 'aboutus',
      text: 'Aboutus'
    },
    {
      id: 'contact',
      path: 'contact',
      text: 'Contact'
    },
    {
      id: 'booking',
      path: 'booking',
      text: 'Booking'
    },
    {
      id: 'photos',
      path: 'photos',
      text: 'Photos'
    }
  ]
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Menu menuItems={menuItems}/>
        {children}
        <Footer/>
        </body>
        
    </html>
  );
}
